# Generated by Django 4.2.23 on 2025-09-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_reservation', '0002_remove_room_amenities_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
