# Generated by Django 4.2.23 on 2025-09-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_reservation', '0003_alter_room_room_type'),
    ]

    operations = [
        # Add index to improve performance of date range queries
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_booking_room_dates ON hotel_reservation_booking (room_id, check_in, check_out) WHERE status IN ('CONFIRMED', 'PENDING');",
            reverse_sql="DROP INDEX IF EXISTS idx_booking_room_dates;"
        ),
        
        # Add index for status filtering
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_booking_status ON hotel_reservation_booking (status);",
            reverse_sql="DROP INDEX IF EXISTS idx_booking_status;"
        ),
    ]
